// <auto-generated />
namespace DemoMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class inicio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inicio));
        
        string IMigrationMetadata.Id
        {
            get { return "201607062301154_inicio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
